export interface SubcategoryConfig {
  id: string;
  name: string;
  shortDesc: string;
  route: string;
  imageSlug?: string;
  category: string;
  brand?: string;
  badge?: string;
  techSpecs?: string[];
  filterCriteria?: {
    category?: string;
    brand?: string;
    subType?: string;
    socket?: string[];
    resolution?: string;
    panelType?: string;
    minRefresh?: number;
  };
}

export interface PrimaryCategoryConfig {
  id: string;
  title: string;
  navLabel: string;
  subtitle: string;
  route: string;
  bannerImage: string;
  category: string;
  color: string;
  description: string;
  subcategories: SubcategoryConfig[];
}

export const CATEGORY_TAXONOMY: PrimaryCategoryConfig[] = [
  {
    id: 'processors-gpus',
    title: 'Processors & GPUs',
    navLabel: 'Extreme Silicon',
    subtitle: 'SELECT THE HARDWARE YOU\'RE LOOKING FOR.',
    route: '/processors-gpus',
    bannerImage: 'CPU_Image/AMD/AMD_Ryzen_9_9950x3d.jpg',
    category: 'cpu',
    color: '#120F17',
    description: 'Unlocked Intel Core, AMD Ryzen & NVIDIA GeForce / AMD Radeon GPUs.',
    subcategories: [
      {
        id: 'processors-amd',
        name: 'AMD Processors',
        shortDesc: 'Ryzen 9000, 7000 & 5000 Series with 3D V-Cache',
        route: '/processors-gpus/processors/amd',
        imageSlug: 'CPU_Image/AMD/AMD_Ryzen_9_9950x3d.jpg',
        category: 'cpu',
        brand: 'AMD',
        badge: 'Socket AM5 / AM4',
        techSpecs: ['Zen 5 / Zen 4 Architecture', '3D V-Cache Technology', 'PCIe 5.0 & DDR5 Support'],
        filterCriteria: { category: 'cpu', brand: 'AMD' },
      },
      {
        id: 'processors-intel',
        name: 'Intel Processors',
        shortDesc: 'Core Ultra Series 2 & 14th Gen Desktop Processors',
        route: '/processors-gpus/processors/intel',
        imageSlug: 'CPU_Image/INTEL/i9_14th_gen.jpg',
        category: 'cpu',
        brand: 'Intel',
        badge: 'LGA1851 / LGA1700',
        techSpecs: ['Performance Hybrid Architecture', 'Turbo Boost up to 6.0 GHz', 'Intel Smart Cache'],
        filterCriteria: { category: 'cpu', brand: 'Intel' },
      },
      {
        id: 'gpu-nvidia',
        name: 'NVIDIA GeForce RTX',
        shortDesc: 'GeForce RTX 40 & 30 Series with DLSS 3.5 & Ray Tracing',
        route: '/processors-gpus/gpu/nvidia',
        imageSlug: 'GPU/Nvidia/rtx_4080_super.jpg',
        category: 'gpu',
        brand: 'NVIDIA',
        badge: 'Ada Lovelace Silicon',
        techSpecs: ['4th Gen Tensor Cores', '3rd Gen RT Cores', 'AV1 Dual Hardware Encoders'],
        filterCriteria: { category: 'gpu', brand: 'NVIDIA' },
      },
      {
        id: 'gpu-radeon',
        name: 'AMD Radeon RX',
        shortDesc: 'Radeon RX 7000 & 6000 Series powered by RDNA 3',
        route: '/processors-gpus/gpu/radeon',
        imageSlug: 'GPU/Radeon/Radeon_RX_7900_xtx.jpg',
        category: 'gpu',
        brand: 'AMD',
        badge: 'RDNA 3 Chiplet',
        techSpecs: ['Chiplet Architecture', 'DisplayPort 2.1 Ready', 'AMD Infinity Cache'],
        filterCriteria: { category: 'gpu', brand: 'AMD' },
      },
    ],
  },
  {
    id: 'thermal-systems',
    title: 'Thermal Systems',
    navLabel: 'Liquid & Air Cooling',
    subtitle: 'KEEP YOUR RIG RUNNING COLD.',
    route: '/thermal-systems',
    bannerImage: 'cooler/NZXT Kraken Elite 360 RGB.jpg',
    category: 'cooler',
    color: '#120F17',
    description: 'Precision AIO radiators, custom coolants, high-CFM fans & thermal paste.',
    subcategories: [
      {
        id: 'air-coolers',
        name: 'Air Coolers',
        shortDesc: 'Dual-tower high-density heatpipes & silent low-profile coolers',
        route: '/thermal-systems/air-coolers',
        imageSlug: 'cooler/Noctua NH-D15.jpg',
        category: 'cooler',
        badge: 'Dual-Tower Heatpipes',
        techSpecs: ['100% RAM Clearance', 'Up to 260W TDP Dissipation', 'Whisper-Quiet NF Fans'],
        filterCriteria: { category: 'cooler', subType: 'air' },
      },
      {
        id: 'aio',
        name: 'AIO Liquid Coolers',
        shortDesc: '240mm, 280mm, 360mm & 420mm closed-loop radiators with LCD pumps',
        route: '/thermal-systems/aio',
        imageSlug: 'cooler/NZXT Kraken Elite 360 RGB.jpg',
        category: 'cooler',
        badge: '240mm - 420mm Radiators',
        techSpecs: ['High-Performance Pump Block', 'Full 2.36" LCD Display', 'ARGB Static Pressure Fans'],
        filterCriteria: { category: 'cooler', subType: 'aio' },
      },
      {
        id: 'case-fans',
        name: 'Case Fans',
        shortDesc: '120mm & 140mm daisy-chain magnetic ARGB chassis fans',
        route: '/thermal-systems/case-fans',
        imageSlug: 'cooler/Lian Li UNI FAN SL-INFINITY 120.jpg',
        category: 'cooler',
        badge: 'Daisy-Chain Interconnect',
        techSpecs: ['Fluid Dynamic Bearings', 'Zero Cable Clutter Design', 'High Static Pressure'],
        filterCriteria: { category: 'cooler', subType: 'fan' },
      },
      {
        id: 'thermal-paste',
        name: 'Thermal Paste',
        shortDesc: 'Premium non-conductive thermal compounds & liquid metal interfaces',
        route: '/thermal-systems/thermal-paste',
        imageSlug: 'Thermal Paste/Thermal Grizzly Kryonaut.jpg',
        category: 'cooler',
        badge: 'High Thermal Conductivity',
        techSpecs: ['14.2 W/mK Conductivity', 'Zero Electrical Conductivity', 'No Curing Required'],
        filterCriteria: { category: 'cooler', subType: 'paste' },
      },
      {
        id: 'custom-cooling',
        name: 'Custom Coolants',
        shortDesc: 'Premixed UV-reactive & clear coolants for open-loop custom reservoirs',
        route: '/thermal-systems/custom-cooling',
        imageSlug: 'coolant/EKWB CryoFuel Clear.jpg',
        category: 'coolant',
        badge: 'Anti-Corrosion Premix',
        techSpecs: ['Biological Inhibitors', 'Long-Term Stability', 'Ultra-Low Electrical Conductivity'],
        filterCriteria: { category: 'coolant' },
      },
    ],
  },
  {
    id: 'memory',
    title: 'Memory',
    navLabel: 'High-Speed Memory',
    subtitle: 'DDR4 & DDR5 PERFORMANCE MODULES FOR GAMING AND WORKSTATIONS.',
    route: '/memory',
    bannerImage: 'Ram/adata/Adata-XPG-Lancer-RGB-ROG-Certified-32GB-16GBx2-DDR5-6600MHz-Desktop-Ram-2.jpg',
    category: 'ram',
    color: '#120F17',
    description: 'High-performance DDR4 and DDR5 memory modules for gaming and workstation builds.',
    subcategories: [
      {
        id: 'ddr5',
        name: 'DDR5 Gaming Memory',
        shortDesc: 'Ultra-high bandwidth 5600MHz - 7200MHz memory for AM5 and LGA1700/1851',
        route: '/memory?type=DDR5',
        imageSlug: 'Ram/adata/Adata-XPG-Lancer-RGB-ROG-Certified-32GB-16GBx2-DDR5-6600MHz-Desktop-Ram-2.jpg',
        category: 'ram',
        badge: 'DDR5 6000+ MT/s',
        techSpecs: ['AMD EXPO & Intel XMP 3.0', 'On-Die ECC Stability', 'Sub-CL30 Low Latency'],
        filterCriteria: { category: 'ram', subType: 'DDR5' },
      },
      {
        id: 'ddr4',
        name: 'DDR4 Performance Memory',
        shortDesc: 'Proven 3200MHz - 3600MHz low-latency kits for AM4 and budget workstation rigs',
        route: '/memory?type=DDR4',
        imageSlug: 'Ram/adata/ADATA-XPG-GAMMIX-D10-8GB-DDR4-3200MHz-AX4U320038G16A-SR10-Desktop-RAM-RED.jpg',
        category: 'ram',
        badge: 'DDR4 3200-3600 MT/s',
        techSpecs: ['Plug-and-Play Overclocking', 'Low Profile Heatspreaders', 'Dual-Channel Optimizations'],
        filterCriteria: { category: 'ram', subType: 'DDR4' },
      },
    ],
  },
  {
    id: 'cables-headers',
    title: 'Cables & Headers',
    navLabel: 'High-Speed Interconnects',
    subtitle: 'CLEAN ROUTING, CHASSIS IO & MODULAR PSU SLEEVED EXTENSIONS.',
    route: '/cables-headers',
    bannerImage: 'Cables/Internal Data, Front Panel & Chassis IO Cables/Front Panel Extension Cable.jpg',
    category: 'cables',
    color: '#120F17',
    description: 'Sleeved PSU extensions, chassis IO splitters, DisplayPort 1.4 & Type-C 40Gbps.',
    subcategories: [
      {
        id: 'psu',
        name: 'PSU Cables & 12V-2x6',
        shortDesc: 'Modular 24-pin ATX, 8-pin EPS & 600W 12VHPWR / 12V-2x6 PCIe Gen 5 cables',
        route: '/cables-headers/psu',
        imageSlug: 'Cables/PSU Cables/Corsair Premium Individually Sleeved Type 4 Gen 4.jpg',
        category: 'cables',
        badge: 'ATX 3.0 / PCIe 5.0 Ready',
        techSpecs: ['16AWG High-Current Wire', 'Flame-Retardant PET Sleeving', 'High-Density Gold Terminals'],
        filterCriteria: { category: 'cables', subType: 'psu' },
      },
      {
        id: 'extensions',
        name: 'Sleeved Extensions',
        shortDesc: 'Universal custom braided extension kits with pre-installed cable combs',
        route: '/cables-headers/extensions',
        imageSlug: 'Cables/PSU Cables/Thermaltake TT Premium Mod Sleeve Cable.jpg',
        category: 'cables',
        badge: 'Universal Compatibility',
        techSpecs: ['Includes 24P, 8P CPU & 8P GPU', 'Closed Acrylic Cable Combs', 'Triple-Layer Weave'],
        filterCriteria: { category: 'cables', subType: 'extensions' },
      },
      {
        id: 'display',
        name: 'Display Cables',
        shortDesc: 'Certified VESA DisplayPort 1.4 / 2.1 & Ultra High Speed HDMI 2.1a cables',
        route: '/cables-headers/display',
        imageSlug: 'Cables/auxx/DisplayPort 1.4 Cable.jpg',
        category: 'cables',
        badge: '4K 144Hz / 8K 60Hz',
        techSpecs: ['48 Gbps Uncompressed Bandwidth', 'Dynamic HDR & VRR Supported', 'Triple Shielded Against EMI'],
        filterCriteria: { category: 'cables', subType: 'display' },
      },
      {
        id: 'usb',
        name: 'USB & Type-C',
        shortDesc: 'USB 3.2 Gen 2x2 & USB4 40Gbps Thunderbolt-compatible interconnects',
        route: '/cables-headers/usb',
        imageSlug: 'Cables/Type-C/Anker 765 USB-C to USB-C Cable (140W Nylon).jpg',
        category: 'cables',
        badge: '100W - 240W Power Delivery',
        techSpecs: ['40 Gbps Data Transfer', 'E-Marker Smart IC Chip', 'Reinforced Strain Relief'],
        filterCriteria: { category: 'cables', subType: 'usb' },
      },
      {
        id: 'internal',
        name: 'Internal Headers & Splitters',
        shortDesc: '4-Pin PWM fan hubs, 3-pin 5V ARGB splitters & front-panel header harnesses',
        route: '/cables-headers/internal',
        imageSlug: 'Cables/Internal Fan, Pump & RGB Header Splitters/4-Pin PWM Fan Splitter Cable.jpg',
        category: 'cables',
        badge: 'PWM & 5V ARGB Hubs',
        techSpecs: ['Motherboard Sync Compatible', 'SATA Powered Current Buffer', 'Adhesive Chassis Mounting'],
        filterCriteria: { category: 'cables', subType: 'internal' },
      },
      {
        id: 'sata',
        name: 'SATA Data & Power',
        shortDesc: 'Locking latch SATA III 6Gbps data cables and multi-drive power splitters',
        route: '/cables-headers/sata',
        imageSlug: 'Cables/Internal Data, Front Panel & Chassis IO Cables/SATA Data Cable 6Gbps.jpg',
        category: 'cables',
        badge: '6 Gbps SATA III',
        techSpecs: ['Precision Steel Locking Latches', '90-Degree Right Angle Connectors', 'Shielded Signal Lines'],
        filterCriteria: { category: 'cables', subType: 'sata' },
      },
    ],
  },
  {
    id: 'displays',
    title: 'Displays',
    navLabel: 'Fast-IPS & OLED Displays',
    subtitle: 'HIGH-REFRESH, COLOR-ACCURATE & ULTRA-FAST ESPORTS MONITORS.',
    route: '/displays',
    bannerImage: 'Monitors/Samsung Odyssey OLED G8 (G80SD).jpeg',
    category: 'monitor',
    color: '#120F17',
    description: 'Ultrawide, 4K UHD, Fast-IPS & 360Hz esports displays with sub-1ms response.',
    subcategories: [
      {
        id: '4k',
        name: '4K Ultra HD',
        shortDesc: '3840 x 2160 pixel resolution for extreme fidelity and workstation clarity',
        route: '/displays/4k',
        imageSlug: 'Monitors/Samsung Odyssey OLED G8 (G80SD).jpeg',
        category: 'monitor',
        badge: '3840 x 2160 UHD',
        techSpecs: ['High Pixel Density (PPI)', 'HDR10+ / VESA DisplayHDR', 'HDMI 2.1 Next-Gen Ready'],
        filterCriteria: { category: 'monitor', resolution: '4K' },
      },
      {
        id: '1440p',
        name: '1440p QHD',
        shortDesc: '2560 x 1440 sweet spot for high-framerate competitive gaming',
        route: '/displays/1440p',
        imageSlug: 'Monitors/ASUS ROG Swift PG27AQDM.jpg',
        category: 'monitor',
        badge: '2560 x 1440 QHD',
        techSpecs: ['Crisp 2K Visuals', '165Hz - 240Hz High Framerates', 'G-Sync Compatible'],
        filterCriteria: { category: 'monitor', resolution: '1440p' },
      },
      {
        id: '1080p',
        name: '1080p Esports',
        shortDesc: '1920 x 1080 Full HD engineered for 240Hz+ esports titles',
        route: '/displays/1080p',
        imageSlug: 'Monitors/BenQ Zowie XL2546K.jpg',
        category: 'monitor',
        badge: '1920 x 1080 FHD',
        techSpecs: ['DyAc+ Motion Clarity', 'Sub-0.5ms Response Time', 'Maximum FPS Headroom'],
        filterCriteria: { category: 'monitor', resolution: '1080p' },
      },
      {
        id: 'oled',
        name: 'OLED & QD-OLED',
        shortDesc: 'Infinite contrast ratio, true 0.03ms pixel response & per-pixel lighting',
        route: '/displays/oled',
        imageSlug: 'Monitors/Samsung Odyssey OLED G8 (G80SD).jpeg',
        category: 'monitor',
        badge: 'True Infinite Contrast',
        techSpecs: ['0.03ms GtG Response Time', 'Pure Inky Blacks', '99% DCI-P3 Color Gamut'],
        filterCriteria: { category: 'monitor', panelType: 'OLED' },
      },
      {
        id: 'ips',
        name: 'Fast-IPS Panels',
        shortDesc: 'Wide 178° viewing angles and 99% sRGB color calibration for creators',
        route: '/displays/ips',
        imageSlug: 'Monitors/LG UltraGear 27GR95QE-B.jpg',
        category: 'monitor',
        badge: '1ms Fast IPS',
        techSpecs: ['Factory Calibrated Color', 'Zero Color Shifting', 'Eye-Care Low Blue Light'],
        filterCriteria: { category: 'monitor', panelType: 'IPS' },
      },
      {
        id: 'ultrawide',
        name: 'Ultrawide 21:9',
        shortDesc: 'Curved panoramic screens for immersion and massive timeline real estate',
        route: '/displays/ultrawide',
        imageSlug: 'Monitors/Samsung Odyssey G9.jpg',
        category: 'monitor',
        badge: '21:9 / 32:9 Panoramic',
        techSpecs: ['1000R Ergonomic Curve', 'Replaces Multi-Monitor Setups', 'Picture-in-Picture Support'],
        filterCriteria: { category: 'monitor', subType: 'ultrawide' },
      },
      {
        id: 'high-refresh',
        name: '240Hz+ High Refresh',
        shortDesc: 'Fluid 240Hz, 360Hz & 500Hz refresh rate tournament-grade monitors',
        route: '/displays/high-refresh',
        imageSlug: 'Monitors/BenQ Zowie XL2546K.jpg',
        category: 'monitor',
        badge: '240Hz - 540Hz',
        techSpecs: ['Ultra-Smooth Tracking', 'Zero Ghosting Technology', 'ELMB Sync Compatibility'],
        filterCriteria: { category: 'monitor', minRefresh: 240 },
      },
    ],
  },
  {
    id: 'warranty-delivery',
    title: 'Warranty & Delivery',
    navLabel: 'Direct Brand RMA',
    subtitle: '100% AUTHENTIC INVENTORY, PAN-INDIA INSURED SHIPPING & DIRECT RMA.',
    route: '/warranty-delivery',
    bannerImage: 'Console/Sony/Playstation_5_pro.jpeg',
    category: 'warranty',
    color: '#120F17',
    description: '100% authentic inventory with pan-India insured shipping and direct brand RMA.',
    subcategories: [],
  },
];
